"""Turn the files Apple gives you into the GitHub secrets the iOS workflow
needs. Run from the repository root after following docs/IOS_RELEASE.md:

    python app/tool/ios_secrets.py

Reads app/ios/signing/: distribution.key (made here), distribution.cer
(from Apple), *.mobileprovision, AuthKey_*.p8. Writes secrets.txt beside
them, one NAME=value per line, to paste into GitHub. Nothing is uploaded."""

import base64
import glob
import os
import secrets
import subprocess
import sys

HERE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "ios", "signing")


def need(pattern, what):
    hits = glob.glob(os.path.join(HERE, pattern))
    if not hits:
        sys.exit(f"missing {what}: put it in {HERE} as {pattern}")
    return hits[0]


key = need("distribution.key", "the private key (generated by the builder)")
cer = need("distribution.cer", "the Apple Distribution certificate downloaded from developer.apple.com")
profile = need("*.mobileprovision", "the App Store provisioning profile")
p8 = need("AuthKey_*.p8", "the App Store Connect API key")
key_id = os.path.basename(p8)[len("AuthKey_"):-len(".p8")]

team = input("Team ID (10 characters): ").strip()
issuer = input("Issuer ID (from App Store Connect > Integrations): ").strip()

pem = os.path.join(HERE, "distribution.pem")
p12 = os.path.join(HERE, "distribution.p12")
password = secrets.token_urlsafe(24)
subprocess.run(["openssl", "x509", "-in", cer, "-inform", "DER", "-out", pem], check=True)
subprocess.run(["openssl", "pkcs12", "-export", "-inkey", key, "-in", pem, "-out", p12,
                "-passout", f"pass:{password}", "-legacy"], check=True)


def b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()


lines = [
    f"APPLE_CERT_P12_BASE64={b64(p12)}",
    f"APPLE_CERT_PASSWORD={password}",
    f"APPLE_PROFILE_BASE64={b64(profile)}",
    f"APPLE_TEAM_ID={team}",
    f"ASC_KEY_ID={key_id}",
    f"ASC_ISSUER_ID={issuer}",
    f"ASC_KEY_P8_BASE64={b64(p8)}",
]
out = os.path.join(HERE, "secrets.txt")
with open(out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out}: paste each line as a repository secret (name = value), then delete the file")
